---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wp01
  namespace: default
  annotations:
    everest.io/disk-volume-type: SAS
  enable: true
  labels:
    failure-domain.beta.kubernetes.io/zone: la-north-2a
    failure-domain.beta.kubernetes.io/region: la-north-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-disk
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: ''
  labels:
    appgroup: ''
    version: v1
  name: wptest
  namespace: default
spec:
  selector:
    matchLabels:
      app: wptest
      version: v1
  template:
    metadata:
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
      labels:
        app: wptest
        version: v1
    spec:
      containers:
        - image: 'jenkins-demo:image'
          name: container-0
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: pvc-wp01
              mountPath: /var/www/html/
              readOnly: false
              subPath: ''
      imagePullSecrets:
        - name: default-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
        - persistentVolumeClaim:
            claimName: pvc-wp01
          name: pvc-wp01
  replicas: 1
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: wptest
  labels:
    app: wptest
  namespace: default
  annotations: {}
spec:
  selector:
    app: wptest
  externalTrafficPolicy: Cluster
  ports:
    - name: cce-service-0
      targetPort: 80
      nodePort: 30001
      port: 80
      protocol: TCP
  type: NodePort
